services:
  - type: web
    name: canary
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: SERPAPI_KEY
        sync: false
